# Generated by Django 3.0.6 on 2020-05-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_Id', models.IntegerField(blank=True, null=True)),
                ('ride_source', models.CharField(max_length=20)),
                ('ride_designation', models.CharField(max_length=20)),
                ('ride_distance', models.IntegerField(blank=True, null=True)),
                ('ride_status', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ride_Id',),
            },
        ),
    ]
